stages:
- test

test:windows:
  stage: test
  only:
  - master
  tags:
  - windows
  script:
  - gem install bundler
  - bundle install

test:mac:
  stage: test
  only:
  - master  
  tags:
  - mac
  script:
  - ls
  - gem install bundler
  - bundle install

test:ubuntu:
  stage: test
  only:
  - master  
  tags:
  - ubuntu
  script:
  - ls
  - gem install bundler
  - bundle install

