version: 2
jobs:
  build:
    working_directory: ~/openstudio-standards
    docker:
      - image: nrel/openstudio:2.6.0
    parallelism: 7
    steps:
      - checkout
      - run:
          name: Install openstudio-standards test dependencies
          command: |
            bundle install
      - run:
          name: Generate test files
          command: |
            bundle exec rake test:gen-circ-files
      - run:
          name: Parallelize Tests
          command: |
            >node_tests.txt
            echo "cat test/helpers/ci_test_helper/$CIRCLE_NODE_INDEX.txt"
            echo "cat test/helpers/ci_test_helper/$CIRCLE_NODE_INDEX.txt > node_tests.txt" | bash
            cat node_tests.txt
      - run:
          name: Run tests
          command: |
            bundle exec rake test:circleci
      - run:
          name: Summarize test times
          command: |
            bundle exec rake test:times
      - run:
          name: Copy test result Timings
          command: |
            cp -R test/reports timing/
      - store_test_results:
          path: test/reports/
      - store_artifacts:
          path: timing/
          destination: test_timing_summary
